.Dd 17 April 2017
.Dt PPBERT 1
.Os

.Sh NAME
.Nm ppbert
.Nd pretty print structures encoded in Erlang's External Term Format
.Sh SYNOPSIS
.Nm
.Op Ar OPTIONS
.Op Ar FILES Nm ...

.Sh DESCRIPTION
.Nm
parses and pretty prints a ETF-encoded file.
The files can either be passed on the command-line
piped through stdin.
.Pp
.Nm
accepts the following options:
.Bl -tag -width Ds
.It Fl h, -help
Display help
.It Fl V, -version
Display version
.El

.Sh RETURN VALUES
.Nm
returns 0 if all files have been successfully processed,
and 1 if any file failed to parse.

.Sh COMPATIBILITY
.Nm
supports a subset of the types supported by the
Erlang External Term Format, namely those that can
represent data structures (see the list below).
.Nm
does not support types such as PIDs, ports,
references, or functions.
.Pp
Supported types:
.Bl -bullet -width Ds
.It
Small integers (tag: 97);
.It
Integers (tag: 98);
.It
Floating-point numbers (tags: 70, 99);
.It
Big integers (tags: 110, 111);
.It
Latin-1 atoms (tags: 100, 115);
.It
UTF-8 atoms (tags: 118, 119);
.It
Strings (tag: 107);
.It
Binaries (tag: 109);
.It
Tuples (tags: 104, 105);
.It
Lists (tags: 106, 108);
.It
Maps (tag: 116).
.El

.Sh EXAMPLES
Pretty print the file foo.bert.
.Pp
.Dl
$ ppbert foo.bert
.Pp
Pretty print from stdin
.Dl
.Pp
$ printf \(dq\ex83\ex77\ex04atom\(dq | ppbert
